Shougo/ddu.vim

denops/ddu/ddu.ts

When the source calls `controller.enqueue()` multiple times such as `Ddu file_rec` in large directory, the ui is not shown on first enqueue.

Call redraw() on first enqueue

---

autoload/ddu.vim
denops/ddu/app.ts
denops/ddu/base/kind.ts
denops/ddu/ddu.ts
denops/ddu/types.ts
doc/ddu.txt

I added `getPreviewer()` function, which returns `Previewer`.
`Previewer` is an interface which defines how the preview is rendered.
```mermaid
sequenceDiagram
ddu-ui->>ddu: ddu#35;get_previewer()
ddu->>ddu-kind: getPreviewer()
ddu-kind->>ddu: Previewer
ddu->>ddu-ui: Previewer
ddu-ui->>ddu-ui: render preview buffer
```

Add preview interface

---

autoload/ddu.vim

If buffer name is i18n-ed, command-line-window detection will fail.

Using `getcmdwintype()` to detect command line window

---

denops/ddu/ddu.ts
doc/ddu.txt

Children items are not sorted/converted even though sorters and converters are specified.
Apply filters to children. But I don't know if matchers should be applied to children, so I excluded them.

Apply filters except for matchers to expanded items

---

denops/ddu/ddu.ts

This comparison is probably the other way around, as we want to test that the `child` is the parent of the `search`.

fix prefix matcher for search and treePath

---

denops/ddu/ddu.ts

基本的な挙動は変えずにリファクタしてみました。
これによりgatherItemsが後続処理を持たなくなるので、refresh時とexpandItem時でgatherItemsを使いまわせ、item収集後の処理は呼び出し元の責務になりました。

refactor gatherItems with async generator

---

denops/ddu/ddu.ts

前段のリファクタリングで並行処理が整理できたので、redraw抑制のためにexpand中のtreePathをSetで管理するのではなく全ての展開処理が終わったらredrawするインターフェースにできました。
Set（expandedPath）はredraw待ちとしての役目は終えますが、tree復元で使用するのに利用する（今も暫定措置で利用されている）ので削除していません。
（[refactor gatherItems with async generator by hori\-ryota · Pull Request \#38 · Shougo/ddu\.vim](https://github.com/Shougo/ddu.vim/pull/38) のマージ ＆ rebase待ち）

Refactor expand item with async

---

denops/ddu/ddu.ts

ここでfalseにしていたのでrefreshする側のtoggle判定に引っかかっていました

fix finished flag bug when resume and refresh

---

denops/ddu/app.ts
denops/ddu/base/column.ts
denops/ddu/base/filter.ts
denops/ddu/base/kind.ts
denops/ddu/base/source.ts
denops/ddu/base/ui.ts
denops/ddu/context.ts
denops/ddu/ddu.ts
denops/ddu/types.ts

There are a lot of `Record<string, unknown>` in the source.
They are defined for different uses, which is confusing.
Define aliases makes it easier to understand type information.
This PR only defines type aliases and replaces it.
No changes in behavior.

refactor: define parameter types

---

denops/ddu/ddu.ts

When item.level is set, use it as is. No addition is necessary.

Respect item.level

---

denops/ddu/ddu.ts

Catch and show error messages in `Source.gather` and `ReadableStream.start`.

feat: catch error of Source.gather and show error messages

---

denops/ddu/types.ts
doc/ddu.txt

I was not clear on the difference between string and string[] in TreePath.
I misunderstood that multiple paths could be specified because sourceOptions.path can be either a string or a string[].
I have noted what it means to use string[] for a parameter or type definition using TreePath, respectively.

Describe two representation ways of the TreePath

---

denops/ddu/ddu.ts

Use events instead of checking flags in a loop, because we can't cancel until the next chunk arrives.
For example, if you run [ddu-soure-rg](https://github.com/shun/ddu-source-rg) in the root directory... the ripgrep process will continue to run even if you quit the UI.

Abort item gathering when quit UI

---

denops/ddu/ddu.ts

Implemented by `TransformStream`.
As a result, try blocks are simpler and signal is easier to handle.
Interrupting by signals works fine.
Related #69.

Refactor gather source.

---

denops/ddu/ddu.ts
denops/ddu/deps.ts

When `sync` options is disabled, `Ddu.redraw()` may be called too many times.
Also waiting for redraw to complete before processing the next gather chunk.
This PR runs redraw asynchronously and scheduled.
Example of execution timing:
```
Gather chunk :             [-A-]          [-B-]          [-C-]
Redraw       : [redraw Pre]     [redraw A]     [redraw B]     [redraw C]
Gather chunk :      [-A-][-B-][-C-]
Redraw       : [redraw Pre][redraw A][redraw C]
Source 1 :      [-A-][-B-][-C-]
Source 2 :       [---D---][---E---]
Source 3 :        [----F----]
Redraw   : [redraw Pre][redraw A][redraw C][redraw E]
```
And `uiRedrawLock` has been renamed to avoid confusion.

Fast redraw

---

doc/ddu.txt

It is difficult to understand how options are handled and how they relate to:
- `ddu#custom#patch_global`
- `ddu#custom#patch_local`
- `ddu#start`
So I have added a sentence explaining it as a FAQ.

Describe how the options be used by ddu.vim

---

denops/ddu/app.ts
denops/ddu/ddu.ts

#81 を大雑把に修正したものです。
gatherが完了していないソースがあるとロックがかかっていてredrawが止まってしまうので、一旦refreshのチェック部分を外に出してみました
ただ、他の問題(例えば、この状態だとactionがブロックされるのでfilter閉じようとすると固まったりする)もあるため根本的な改善が必要だと思われます。

RFC: 走ってるソースあってもvolatile効くようにしてみた

---

denops/ddu/ddu.ts

When I use column as filer, parent item's column is not be updated.
So I fix it.
before
after

fix column when fire expandItem action

---

denops/ddu/ddu.ts

Before this commit, to get preview we get kind name from source's kind only.
So if I want to custom each items via other sources but still don't want to change the item's kind, I can't do that.
For example, the other sources is [ddu-source-custom_params](https://github.com/kamecha/ddu-source-custom_params)
From this commit, we can get kind name from source's kind or from item's kind. So we can custom each items via other sources.

fix: use item.kind (if available) instead of source.kind to get preview

---

denops/ddu/app.ts
denops/ddu/ddu.ts
denops/ddu/deps.ts

- Source initialization and items gathering asynchronously, and reduces the time it takes to show the first results.
- Abort the asynchronous process using the signal at the start, which allows for correct cancellation.
This PR has a lot of changes. Therefore, I would like to keep it as a draft until it is confirmed that there are no problems with execution.

Initialize sources as stream and fixes abort

---

denops/ddu/ddu.ts
denops/ddu/state.ts

This is fixes bug in #107 (and refactor for 39bc2b7).
There is no need to check `signal.aborted`.
1. "quit" then aborts all states.
2. "cancel" by "redraw" then clear all states, because all states aborted when (1).

fix: revert refresh target check in cancel

---

autoload/ddu.vim

fix: call `ddu#denops#_mods` instead of referring as a variable

---

doc/ddu.txt

In doc, the first `{name}` parameter of `ddu#load` is missing.

doc: Add missing "name" parameter of ddu#load

---

denops/ddu/base/config.ts

Exported type of `setAlias` property in `ConfigArguments` type doesn't have the first `name` argument.  Therefore this is different from the type of `setAlias` defined in `denops/ddu/app.ts`.  This PR fixes this.

fix: Missing "name" argument of setAlias in ConfigArguments

---

denops/ddu/app.ts

When calling `ddu.vim`'s `start` function with `push=true`, the `context.winId` is incorrectly set to the `winId` of an already open `ddu.vim` instance. This results in the return window selection being incorrect after closing the `ddu.vim` window.
To address this issue, the `winId` is now carried over from the previous `ddu` context when `push=true`. This ensures that the `context.winId` remains consistent with the previously opened `ddu` instance, allowing the return window to be selected correctly.
Tests and verifications have been conducted to ensure that the `winId` is correctly carried over and that the return window selection works as expected.
```
:new
:wincmd j
:call ddu#start(...)
:call ddu#ui#do_action("chooseAction")
:q
:q
```

Fix: Ensure winId is carried over to the pushed context

---

denops/ddu/app.ts
denops/ddu/ddu.ts
denops/ddu/ext.ts
denops/ddu/state.ts

Enabled cancellation of gather sources by locking only the UI during refresh, not the entire refresh process.
This PR includes 3 cumulative commits.  If necessary, these can be separated into individual PRs.

fix: gather sources does not cancelled on refresh
