denops/ddu/ddu.ts
=> Fix initial redraw on async source

denops/ddu/ddu.ts
To execute `ui.searchPath` when update `ddu-option-searchPath`.
=> update searchPath when option updated

denops/ddu/ddu.ts, denops/ddu/deps.ts
=> improve pathmatcher and seach level calculator

denops/ddu/ddu.ts
expandedPathsを状態管理に利用し、 `__expanded` が正しくなるようにしました。
=> fix `__expanded` mismatch bug

denops/ddu/ddu.ts
ちょいちょい干渉している気配がしたので起動に関するものとcontextの制御に利用するものを分けました
=> refactor flags to cancel context

denops/ddu/ddu.ts, denops/ddu/types.ts, doc/ddu.txt
- redraw周りを「ui側も含めたデータの更新」と「uiのredraw」に整理しました
- 「ui側も含めたデータの更新」処理でexpandとsearch対象の解決をしました
これ自体は良さそうなのですが、再表示でrefreshが発生すると挙動がおかしい問題に当たったので、ちょっと調査します
https://github.com/Shougo/ddu.vim/blob/7d1b1fab5f1098e0c8c12246e34a78acfd144584/denops/ddu/ddu.ts#L150
=> Refactor redraw with search

denops/ddu/ddu.ts
- narrow時のexpandedPath管理をsourceOptions.pathごとに管理していたが、filerなどでは絶対パスで管理されているので必要なかった
- むしろexpandItem時にgatherItemにわたすsourceOptionsはpathを書き換えているので不具合になっていた
- → シンプルなset管理に戻した
- narrowで親ディレクトリに移動し、expandedな子要素を持つitemをexpandした場合maxLevelによりexpandedなものは展開されないが、状態はexpandedになっているという不整合が生じていた
- → expandする際、maxLevelにより展開されなかった子要素は明示的にcollapseしておくようにした
> - → expandする際、maxLevelにより展開されなかった子要素は明示的にcollapseしておくようにした
ここの挙動ですが、collapseするかmaxLevelを尊重するかは意見が分かれそうに思います。
別解として現在のrootに対してexpandedPathを管理する方法もありそうです（sourceOptionsでやろうとしていたこと。何らかの方法で現在のrootを取れれば実現できそう）。
個人的な使用感としてはcollapseする方針ならmaxLevelとsearchの設定で各々が調整できるので良さそうに思っています。
=> fix expandedPath mismatch

doc/ddu.txt
Fix types in help on multiple commits.
If there are unnecessary changes, I will delete it.
=> fix types in help

autoload/ddu/ui.vim, doc/ddu.txt
`ddu#ui_action` is not already defined. (c1256ca4daec6d9f4b82d3f7342f4c32a5a367f8)
=> Fix ddu#ui_action -> ddu#ui_sync_action

denops/ddu/ddu.ts
=> Remove a floating promise in `autoload`

doc/ddu.txt
=> docs: Fix function name mistyped

denops/ddu/base/source.ts, denops/ddu/ddu.ts
=> fix: Expose loader to Source.onInit

denops/ddu/app.ts, denops/ddu/base/filter.ts, denops/ddu/loader.ts
https://github.com/Milly/ddu-filter-merge needs module path.
=> include module path in `getXXX` returned values

denops/ddu/ddu.ts
=> Fix unnecessary triggered modeline evaluation

doc/ddu.txt
=> fix doc for order between columns and filters

doc/ddu.txt
I think currently missing information about column order.
Therefore, I added preliminary documentation on how to apply the column.
Maybe I should write it somewhere else, but I'll write it here for now.
=> Update doc for columns

.github/workflows/deno.yml, deno.jsonc
To conveniently run check and test.
e.g. Windows environment.
=> feat: add deno.jsonc

denops/ddu/ddu.ts, denops/ddu/state.ts
If only some states are canceled, other states that was not canceled could not be canceled again.
=> Reset signal if only some states are canceled

autoload/ddu/util.vim, denops/ddu/context.ts, denops/ddu/ddu.ts, denops/ddu/ext.ts, denops/ddu/utils.ts
Add `printError()` wrapper function, and use it instead call vim function directory.
Then output the error text break lines for humans readable.
=> Use `printError()` wrapper function instead call vim function

denops/ddu/ddu.ts
21cb759 is an over-correction.
This PR reconsiders the binding timing of signal and clarifies it with a NOTE comment.
=> fix: Fix by considering the period of signal

autoload/ddu/ui.vim
=> fix: Unify return type of ddu#ui#get_items()

.github/workflows/jsr.yml, README.md, deno.jsonc, denops/ddu/app.ts, denops/ddu/base/action.ts, denops/ddu/base/column.ts, denops/ddu/base/config.ts, denops/ddu/base/filter.ts, denops/ddu/base/kind.ts, denops/ddu/base/source.ts, denops/ddu/base/ui.ts, denops/ddu/context.ts, denops/ddu/ddu.ts, denops/ddu/deps.ts, denops/ddu/ext.ts, denops/ddu/loader.ts, denops/ddu/state.ts, denops/ddu/types.ts, denops/ddu/utils.ts, doc/ddu.txt
=> Migrate to JSR

doc/ddu.txt
=> doc: Explain the matchers can process user input as needed

denops/ddu/ext.ts
=> fix: filters can return empty string as valid input for subsequent filters

.github/workflows/deno.yml, .github/workflows/jsr.yml, README.md, autoload/ddu/denops.vim, deno.jsonc, denops/ddu/app.ts, denops/ddu/base/column.ts, denops/ddu/base/config.ts, denops/ddu/base/filter.ts, denops/ddu/base/kind.ts, denops/ddu/base/source.ts, denops/ddu/base/ui.ts, denops/ddu/context.ts, denops/ddu/ddu.ts, denops/ddu/deno.json, denops/ddu/ext.ts, denops/ddu/loader.ts, denops/ddu/types.ts, denops/ddu/utils.ts, doc/ddu.txt
Require the latest denops.vim.
=> Add import map support
